### ISSUE TITLE
Add ping-loop plugin

### ISSUE THREAD

**Issue by belak** [seabird-chat/seabird-plugin-bundle#27]
Additionally, seabird should properly shut down after a ping timeout. Error handling will have to be reworked a bit for this to be possible.

**Comment by NickLanam** [comment]
Relevant:
https://github.com/jsvana/async-minecraft-ping

**Comment by jsvana** [comment]
@belak do you just mean a plugin to respond to IRC server pings? @NickLanam thanks for the plug :) I'm not sure that this is the same ping, though.

**Comment by belak** [comment]
Sort of. We already respond to pings. This would be to send our own pings.

**Comment by jsvana** [comment]
Pings to what? Sorry, not following :)

**Comment by belak** [comment]
We need to send irc server pings to make sure the connection is still open

**Comment by belak** [comment]
IRC pings are way too tied to the protocol - I think this is a hold over from when this was just an irc bot.
