### ISSUE TITLE
Port plugins from go-seabird

### ISSUE THREAD

**Issue by belak** [seabird-chat/seabird-plugin-bundle#5]
- [x] Basic url plugin
- [x] Forecast/weather
- [x] Runescape
- [ ] Issues

Dropped:
- [x] Dice

**Comment by jsvana** [comment]
Should `reminder` and `chance` (mostly roulette) be included here?

**Comment by xInferno** [comment]
+1'ing for !issue in particular.

**Comment by belak** [comment]
Closing this in favor of #40
